#!/bin/sh

function bp_git_dirty {
    [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit, working tree clean" ]] && echo "*"
}

function bp_git_branch {
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1/"
}

function bp_git_repo {
    git config --get remote.origin.url | cut -f2 -d: | cut -f1 -d.
}

function bp_git_info {
    [[ $(git status 2> /dev/null) != "" ]] && echo " [git] $(bp_git_repo):$(bp_git_branch)$(bp_git_dirty) "
}

function venv_info {
    python -c 'import sys; print sys.real_prefix' > /dev/null 2>&1 && echo " [venv] `basename "$VIRTUAL_ENV"` "
    #basename "$VIRTUAL_ENV"
}

red_fg=$(tput setaf 1)
red_bg=$(tput setab 1)
green_fg=$(tput setaf 2)
green_bg=$(tput setab 2)
yellow_fg=$(tput setaf 3)
yellow_bg=$(tput setab 3)
blue_fg=$(tput setaf 4)
blue_bg=$(tput setab 4)
magenta_fg=$(tput setaf 5)
magenta_bg=$(tput setab 5)
cyan_fg=$(tput setaf 6)
cyan_bg=$(tput setab 6)
white_fg=$(tput setaf 7)
white_bg=$(tput setab 7)
reset=$(tput sgr0)
bold=$(tput bold)

# turn off default virtualenv prompt stuff
export VIRTUAL_ENV_DISABLE_PROMPT=1

export PS1='\n\[$reset\]\[$yellow_bg\]\[$blue_fg\]$(venv_info)\[$reset\]\[$blue_bg\]\[$white_fg\] [host] $(hostname) \[$reset\]\[$red_bg\]\[$white_fg\] [user] \u \[$reset\]\[$cyan_bg\]\[$white_fg\] [pwd] \w \[$reset\]\[$magenta_bg\]\[$white_fg\]$(bp_git_info)\[$reset\]\n\n\[$green_fg\]\[$reset\] '
