#!/bin/sh

function bp_git_dirty {
	[[ $(git status 2> /dev/null | tail -n1) != "nothing to commit, working directory clean" ]] && echo "*"
}

function bp_git_branch {
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1/"
}

function bp_git_repo {
	git config --get remote.origin.url | cut -f2 -d: | cut -f1 -d.
}

function bp_git_info {
	[[ $(git status 2> /dev/null) != "" ]] && echo " [git] $(bp_git_repo):$(bp_git_branch)$(bp_git_dirty) "
}

export PS1='\n\033[1;0m\033[44m [host] $(hostname) \033[0m \033[41;1m [user] \u \033[0;1m \033[46m [pwd] \w \]\033[0m \033[45m$(bp_git_info)\033[0m \033[0;32m\n\n\033[0m\033[0;33m '
