#!/bin/sh

export PATH=/opt/local/bin:/opt/local/sbin:~/Projects/dotfiles/bin:$PATH
export JAVA_HOME=$(/usr/libexec/java_home)


# update macports, port tree, & installed packages
alias update-macports='sudo port selfupdate && sudo port upgrade outdated'

# directory listing - show all files but ignore .DS_Store
alias ll='ls -lA | grep -v .DS_Store'

alias gsu='git submodule update --init --recursive'

# git completion - enables tab completion for git branch names
source ~/.git-completion.sh

# custom bash prompt
source ~/Projects/dotfiles/osx/bash_prompt

# append local profile if it exists
[ -f ~/.local_profile ] && source ~/.local_profile
